USE ORM;

CREATE TABLE IF NOT EXISTS users (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  address TEXT NOT NULL,
  dob DATETIME NOT NULL,
  email VARCHAR(255) NOT NULL,
  `createdAt` DATETIME NOT NULL,
  `createdBy` INT NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  `updatedBy` INT NOT NULL
);

CREATE TABLE IF NOT EXISTS employees (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  position VARCHAR(255) NOT NULL,
  department VARCHAR(255) NOT NULL,
  salary DOUBLE NOT NULL,
  `createdAt` DATETIME NOT NULL,
  `createdBy` INT NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  `updatedBy` INT NOT NULL
);
